### ISSUE TITLE
Change condition on `kernel-patches/bpf` check to detect if Linux sources should be downloaded

### ISSUE THREAD

**Issue by qmonnet** [kernel-patches/vmtest#41]
Context: I'm reusing some of the CI infra for a Linux fork on my own GitHub account.

Following commit https://github.com/kernel-patches/vmtest/commit/fa07d13393d0cf5053e9e4b2e396279af940296b, the description of the GitHub workflow has the following snippet to allow the CI to run on the `vmtest` repository.

```yaml
      - name: Get bpf-next source
        if: ${{ github.repository != 'kernel-patches/bpf' }}
        uses: actions/checkout@v2
        with:
          repository: kernel-patches/bpf
          ref: 'bpf-next'
          path: 'linux'
      - name: Move linux source in place
        if: ${{ github.repository != 'kernel-patches/bpf' }}
        run: rsync --exclude .git -av linux/. . && rm -rf linux
```

This makes the Action download kernel sources before compiling and running the checks, if `github.repository != 'kernel-patches/bpf'`.

It is rather easy to copy all files from `vmtest` to another Linux repository and to run the same CI checks from another GitHub account by creating a dedicated PR (e.g. https://github.com/qmonnet/linux/pull/4, the branch was manually created, without the Patchwork parts of the CI), except that the above check will overwrite the Linux sources (and the modifications to test). It's not  hard to remove this check before copying the file and running the action, but it makes the operation less straightforward.

Would it be possible to adjust this check? One solution could be to have `if: ${{ github.repository == 'kernel-patches/vmtest' }}`, although the same issue would arise again if someone tried to run the checks on e.g. a fork of `vmtest`. Alternatively, would it be possible to check whether the repository seems to contain the Linux sources? E.g. by looking at a few known files maybe?
